### ISSUE TITLE
Day 03 - MicroK8s Public DNS

### ISSUE THREAD

**Issue by ironpeak** [hgop/syllabus-2020#1]
Each group should leave comment here:
~~~
Public DNS: your-ec2-instance.eu-west-1.compute.amazonaws.com
Team Name: dreamteam
~~~
Where the `Team Name` is something unique (hasn't been commented before).
We'll setup a CNAME record for dns so that `team-name.hgopteam.com` will point to your cluster, we will put a thumbs up on your comment once its done (it may take a couple of minutes to propagte over the internet)

**Comment by ironpeak** [comment]
~~~
Public DNS: ec2-52-214-51-183.eu-west-1.compute.amazonaws.com
Team Name: dreamteam
~~~

**Comment by kthorri** [comment]
```
Public DNS: ec2-3-249-244-223.eu-west-1.compute.amazonaws.com
Team Name: dr3amt3am
```

**Comment by kthorri** [comment]
:shipit:

**Comment by hjaltist** [comment]
```
Public DNS: ec2-3-229-123-29.compute-1.amazonaws.com
Team Name: cicd
```

**Comment by thoalr** [comment]
public DNS: ec2-3-235-245-111.compute-1.amazonaws.com
Team Name: pair10

**Comment by birtaosk93** [comment]
public DNS: ec2-3-236-226-135.compute-1.amazonaws.com
Team Name: pair5

**Comment by palli710** [comment]
public DNS: ec2-3-235-144-219.compute-1.amazonaws.com
Team Name: pair4

**Comment by ArnthorDadi** [comment]
Public DNS: ec2-34-231-243-165.compute-1.amazonaws.com
Team Name: ikea

**Comment by tinnarve** [comment]
Public DNS: ec2-54-175-206-188.compute-1.amazonaws.com
Team Name: NaN-braud

**Comment by Izabela17** [comment]
Public DNS: ec2-3-238-181-142.compute-1.amazonaws.com
Team Name: queenteam

**Comment by holmar18** [comment]
Public DNS : ec2-52-55-2-196.compute-1.amazonaws.com
Team Name : Pair3

**Comment by baldurhar18** [comment]
Public DNS: ec2-3-81-0-188.compute-1.amazonaws.com
Team Name: pair8

**Comment by arnara18** [comment]
Public DNS: ec2-3-235-20-135.compute-1.amazonaws.com
Team Name: 2

**Comment by ironpeak** [comment]
> 
> 
> Public DNS: ec2-3-235-20-135.compute-1.amazonaws.com
> Team Name: 2

Your team name is "two"

**Comment by joningi98** [comment]
Public DNS: ec2-54-152-97-67.compute-1.amazonaws.com
Team Name: bois

**Comment by baldvinw** [comment]
Public DNS: ec2-52-90-102-158.compute-1.amazonaws.com
Team Name: pair9

**Comment by soleyhr** [comment]
Public DNS: ec2-3-238-49-107.compute-1.amazonaws.com
Team name: clueless

**Comment by palli710** [comment]
Public DNS: ec2-3-226-250-156.compute-1.amazonaws.com
Team name: pair_4

**Comment by ironpeak** [comment]
> 
> 
> Public DNS: ec2-3-226-250-156.compute-1.amazonaws.com
> Team name: pair_4

Updated "pair4" with your new Public DNS

**Comment by ingi17** [comment]
Public DNS: ec2-34-231-247-119.compute-1.amazonaws.com
Team name: Stoduvaelamordur

**Comment by ingibjorg88** [comment]
Public DNS: ec2-3-239-49-46.compute-1.amazonaws.com
Team name: what

**Comment by Gvendur** [comment]
redo
public DNS: ec2-100-24-41-236.compute-1.amazonaws.com
Team name: ikea

**Comment by ironpeak** [comment]
Please create a new issue, if you need to update your DNS.

I don't get notified for new comments on this issue.
