### ISSUE TITLE
Day3 - AWS - Not Authorized to perform  operation

### ISSUE THREAD

**Issue by soring** [hgop/syllabus-2020#11]
# Expected Behaviour
Being able to run **terraform apply** 

# Current Behaviour
Terraform throws an error. Indicates this is a permission issue. The error also thrown in AWC Console on web.

## Context

I've followed the instructions for day 3 to the letter. Still get an error with an encoded error message. I'm able to create a t1.micro instance on the AWS Console, but get the same error when trying to create the t3.medium instance.

My test code is available here (TA's have access): https://github.com/ContinuousInvestigationContinuousDebug/infrastructure/tree/testing/soring

* Operating System: Ubuntu 20.04
Terraform v0.13.5
- provider registry.terraform.io/hashicorp/aws v3.17.0
aws-cli/1.18.185 Python/2.7.18 Linux/5.4.0-54-generic botocore/1.19.25

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

1. Open AWS Console and create t3.medium instance or run terraform apply with the config supplied in day3 assignment

## Failure Logs

![image](https://user-images.githubusercontent.com/3142341/100215747-50b23700-2f09-11eb-9277-7f674b411462.png)

**Comment by soring** [comment]
t2.medium works - we will continue using that instance. It has the same number of cpus and amount of mem. It's lower network io and disk io. But that should not be an issue for the load we expect on these services.

**Comment by ironpeak** [comment]
it's fine if you use t2.medium, we tested this using t3.medium but there should not be an impactful difference for the assignment.
