### ISSUE TITLE
Step 10 - k8s.yaml.template

### ISSUE THREAD

**Issue by Izabela17** [hgop/syllabus-2020#13]
How do we add this to our docker? 
Do we have to build the docker again or use apply command as we did for Kubernetes?
A bit lost about what should be done here to connect it to docker.
Thanks!

**Comment by ironpeak** [comment]
In day 2 you created a docker hub account and a repository that you pushed the client image to.

If you did those steps you just need to change the `image:` field in the yaml file to point to your docker repository, no need to build anything again if you completed day 2.

**Comment by Izabela17** [comment]
If I have created the docker hub account and pushed my docker image there and have changed the image: field and gave it the correct reference and is still not working there is probably a problem with my dockerfile or the yaml.template?
I just feel like I'm missing a step - how does the docker image know that the yaml.template is there? Don't we have to run the yaml.template somehow in the docker as we did for kubernetes when we used apply to deploy the yaml to the cluster?

**Comment by birtaosk93** [comment]
I think you have to do the "kubectl apply" command on the new yaml file and make sure you have the correct ports.

**Comment by ironpeak** [comment]
The docker image should not know about/use the yaml.template file. Your docker image is a "computer" that runs a server hosting your client.

The yaml.template is created for kubernetes where you have:
- Ingress: the url to service:port mapping
- Service: the service:port to deployment:port mapping
- Deployment: which image your pod should use

**Comment by ironpeak** [comment]
@Izabela17 are you able to run the docker image you created on day 2 on your computer?

~~~bash
docker run {username}/{repository}:{tag}
~~~

**Comment by Izabela17** [comment]
yes, I can run in no problem. I think the problem for me was I misunderstood the assignment. I thought because I have used apply with yaml script on Kubernetes I should not do it again and the other part was focusing mostly on docker that's is why I was so confused since I could not find any yaml/docker/ingress trio online without Kubernetics :)
