### ISSUE TITLE
Day 3 - Step 10

### ISSUE THREAD

**Issue by arnara18** [hgop/syllabus-2020#16]
I'm having issues in step 10. Everything worked in step 9 with the httpbin but when I put in my image from day 2 it looks like its working in the terminal however when I load the page it gives me a 502 error. The docker image seems to be working on its own so I don't understand what is happening. 
### k8s.yaml.template
![Screenshot from 2020-11-26 18-32-11](https://user-images.githubusercontent.com/42962972/100383759-547faf80-3016-11eb-9208-a80f7c4b9e37.png)
![Screenshot from 2020-11-26 18-32-36](https://user-images.githubusercontent.com/42962972/100383760-55b0dc80-3016-11eb-9b35-2788585c81a3.png)

### kubectl logs connect4-65b477cc97-st7wj
![Screenshot from 2020-11-26 18-33-33](https://user-images.githubusercontent.com/42962972/100383761-56497300-3016-11eb-849b-f7701c0e2cfb.png)
![Screenshot from 2020-11-26 18-34-21](https://user-images.githubusercontent.com/42962972/100383762-56e20980-3016-11eb-82d7-3f8f31fae5fc.png)

### http://connect4.two.hgopteam.com/
![Screenshot from 2020-11-26 18-34-58](https://user-images.githubusercontent.com/42962972/100383764-577aa000-3016-11eb-9bb9-8f40dd6932a5.png)

**Comment by kthorri** [comment]
When you run it individually, are you accessing a specific port?

If so, is that port being used in your template file?

**Comment by ironpeak** [comment]
Can you add a link to the repository?

**Comment by arnara18** [comment]
Was able to fix it. Needed to change the container/target port :)
