### ISSUE TITLE
Day 4: Deploy to kubernetes

### ISSUE THREAD

**Issue by tinnarve** [hgop/syllabus-2020#17]
Does anyone know what this might be? We have been following the assignment description and have gotten build and publish to successfully work.
![image](https://user-images.githubusercontent.com/34030683/100396991-6aee3100-303f-11eb-8523-56d2dd4b78cc.png)

**Comment by Fanneyyy** [comment]
Are you sure we've finished this part:

> We need to add our `KUBECONFIG_DATA` to the Circle CI environment variables.
The Kube config is the file we use locally to access our kubernetes cluster. It should be secret and the way we add it to Circle CI is to base64 encode it and add it to environment variables. You can use this command:
```
cat ~/.kube/config | base64
```

**Comment by koffa95** [comment]
Yes. We'we added the outcome of the cat to an env variable called KUBECONFIG_DATA . We get a different error if it's not in there

**Comment by Fanneyyy** [comment]
Can you send me the outcome on Slack, it looks like it's not correctly base64 encoded

**Comment by Fanneyyy** [comment]
This was an issue with base64 encoding, if you have this issue please comment on this issue.

**Comment by arnara18** [comment]
Hi, we are having the same issue! We have set the enviromental variable but we are getting the same error in circle ci
