### ISSUE TITLE
Aðstoð

### ISSUE THREAD

**Issue by lilja16** [hgop/syllabus-2020#18]
Verður hægt að fá aðstoð í dag á zoom? :) 
Klukkan hvað þurfum við að vera búin að skila lab1?

**Comment by ironpeak** [comment]
Þurfið að submitta skilunum inná canvas í dag.

Getið haldið áfram með verkefnið fram að hádegi á morgun (þá byrjum við að fara yfir)

**Comment by ironpeak** [comment]
Fanney ættlar að reyna að komast á fyrri fundinn (kemur líklega 13:30)

Ég kem á seinni kl 16.
