### ISSUE TITLE
Varðandi skilin í kvöld

### ISSUE THREAD

**Issue by solrun18** [hgop/syllabus-2020#19]
Hæhæ, við erum með nokkrar spurningar varðandi skilin í kvöld?

1. Er nauðsynlegt að kommenta allar línur í scriptinu fyrir day01 (allar install og version)?
2. Þurfa allir að submita github issue hér á instructure github?
3. Samkvæmt filestructure-inu í day03 þá er aldrei minnst á httpbin.yaml, á hún að vera í .gitignore?

**Comment by ironpeak** [comment]
1. Þarf bara að sjást að þið skiljið hvað er að gerast
2. Bara hver hópur (lýsing í day 1)
3. Það verður ekki farið yfir hana, hún má vera í infrastructure repo-inu ef þið viljið

**Comment by ironpeak** [comment]
Það er engin mínus fyrir auka file í repositories sem þið búið til, nema þeir séu eitthvað eins og `node_modules` eða secrets sem eiga ekki að vera partur af repository-inu.

Við förum ekki yfir git history, nema bara til að sjá að báðir aðilar hafi gert eitthvað, ef þið setjir óvart inn þessa file þá er nóg að delete-a þeim og commita aftur þið þurfið ekki að modify-a git history. En utan skóla þá væri það ekki nóg til að hreinsa secret út úr repository.
