### ISSUE TITLE
Error while running "pip install -r requirements.txt"

### ISSUE THREAD

**Issue by arnara18** [hgop/syllabus-2020#22]
We get an error while installing the requirements for the server. 

**Command:** 
pip install -r requirements.txt

**Output:**
Collecting Flask==1.1.2
  Using cached Flask-1.1.2-py2.py3-none-any.whl (94 kB)
Collecting flask-cors==3.0.9
  Using cached Flask_Cors-3.0.9-py2.py3-none-any.whl (14 kB)
Collecting psycopg2==2.8.6
  Using cached psycopg2-2.8.6.tar.gz (383 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/arnarut/Desktop/hr/connect-four-server/connect-four-server-base/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pg7pzxmg/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pg7pzxmg/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-pg7pzxmg/psycopg2/pip-egg-info
         cwd: /tmp/pip-install-pg7pzxmg/psycopg2/
    Complete output (23 lines):
    running egg_info
    creating /tmp/pip-install-pg7pzxmg/psycopg2/pip-egg-info/psycopg2.egg-info
    writing /tmp/pip-install-pg7pzxmg/psycopg2/pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-install-pg7pzxmg/psycopg2/pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-install-pg7pzxmg/psycopg2/pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file '/tmp/pip-install-pg7pzxmg/psycopg2/pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    
    Error: pg_config executable not found.
    
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by stefank17** [comment]
pg_config missing
Try this:
sudo apt-get install libpq-dev
pip install -r requirements.txt

**Comment by ironpeak** [comment]
requirements_dev.txt would be a better place for it as it should only be required on your development machine.

Then you'll also need to install requirements_dev.txt before installing requirements.txt on your development machine.
