### ISSUE TITLE
 ImagePullBackOff status on the Server pod

### ISSUE THREAD

**Issue by baldurhar18** [hgop/syllabus-2020#24]
![image](https://user-images.githubusercontent.com/42969947/100755590-3f26ce80-33e4-11eb-950c-11044c4874cb.png)

![image](https://user-images.githubusercontent.com/42969947/100755752-6da4a980-33e4-11eb-975e-a6d8d57fc349.png)

can anyone tell me if this two things connect?

What is the thing to do if I am getting this ImagePullBackOff status on the Server pod?

**Comment by ironpeak** [comment]
í fyrri gerðu:

~~~bash
kubectl describe pod {{name}}
~~~

Í seinna er kubeconfig ekki set upp, en þetta er ekki tengt fyrra vandamálinu.

**Comment by ironpeak** [comment]
postaðu svo outputinu úr describe pod hér.

**Comment by kthorri** [comment]
@baldurhar18 er þetta ekki resolved?
