### ISSUE TITLE
Timeout on URLs despite running pods.

### ISSUE THREAD

**Issue by ingi17** [hgop/syllabus-2020#26]
# Expected Behaviour
connect4.stoduvaelamordur.hgopteam.com and connect-four-server-production.stoduvaelamordur.hgopteam.com correctly hosting the app.

# Current Behaviour
After following the day06 instructions both URLs do not load. No NGINX error just a server timeout.

## Context
* Pods
I'm unsure about the duplicate httpbins with evicted and invalidimagename. To the best of my knowledge they shouldn't affect this but I would gladly stand corrected on that.
![image](https://user-images.githubusercontent.com/34063026/100783757-18798f80-3406-11eb-94bb-12f32b5fea5d.png)

* Ingress Pod
![image](https://user-images.githubusercontent.com/34063026/100784200-bf5e2b80-3406-11eb-9554-12a0e0b6cf0a.png)

* Microk8s & AWS
![image](https://user-images.githubusercontent.com/34063026/100784320-ea487f80-3406-11eb-91f0-75006b2fe5a3.png)

* Services
![image](https://user-images.githubusercontent.com/34063026/100784427-1401a680-3407-11eb-9ec2-92e53e2d3eba.png)

* Deployment
![image](https://user-images.githubusercontent.com/34063026/100784479-27ad0d00-3407-11eb-9b06-ec5545649bd1.png)

* Ingress 
![image](https://user-images.githubusercontent.com/34063026/100784594-52976100-3407-11eb-906a-ab7cb6a96879.png)

# Failure Information
Running the applications locally through npm start and docker-compose up --build displays the applications as expected though. Problem most likely in kubectl, microk8s etc. setup.  
  
I had the same issue as was noted in #25 and followed the steps from there as well as #23.  
Although originally my evicted reason was due to ephemal-storage (The node was low on resource: ephemeral-storage. Container nginx-ingress-microk8s was using _____, which exceeds its request of 0.) that was fixed via an instance restart.

**Comment by ironpeak** [comment]
https://github.com/hgop/syllabus-2020/issues/25

**Comment by ironpeak** [comment]
Everything is up and running :)

(I didn't do anything)

**Comment by ironpeak** [comment]
https://github.com/hgop/syllabus-2020/issues/29
