### ISSUE TITLE
connect-four-server test failed

### ISSUE THREAD

**Issue by soleyhr** [hgop/syllabus-2020#27]
Hæhæ Hrafn Orri var að hjálpa okkur til að fá leikinn til að virka í dag/gær en við fengum svo þessa villu og þorum ekki alveg að rugla meira í  servernum því það var smá bras að laga þetta hjá okkur :)
getum við fengið hjálp sem fyrst?

npm ERR! path /home/circleci/project/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/circleci/project/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2020-12-01T22_36_14_582Z-debug.log

Exited with code exit status 254
CircleCI received exit code 254

**Comment by Fanneyyy** [comment]
Hæhæ, test skrefið sem þið eruð að keyra í circle ci fyrir connect-four-server er ætlað fyrir clientinn, python keyrir testin öðruvísi, hér er parturinn í verkefninu sem sýnir hvernig eigi að keyra testin fyrir python: https://github.com/hgop/syllabus-2020/blob/master/assignments/week-02/day-07/README.md#part-3---setup-unit-tests-job-in-circleci
