### ISSUE TITLE
If you need an instance with more space

### ISSUE THREAD

**Issue by ironpeak** [hgop/syllabus-2020#29]
If you need a microk8s instance with more space I'll set one up for you:

Just comment your team name and a link to your infrastructure repository here and I will create a new instance with more space (since aws educate does not allow students to modify disk size).

This mean you will have to install microk8s again on the instance, generate a new kubeconfig and setup the database again.

~~~
dreamteam
github.com/hgop/infrastructure
~~~

I will post the pem file as an issue to your infrastructure repository (make sure it's private)

**Comment by ingi17** [comment]
```
stoduvaelamordur
https://github.com/ingi17/infrastructure
```

**Comment by solrun18** [comment]
queenteam 
https://github.com/solrun18/infrastructure

**Comment by solrun18** [comment]
queenteam
https://github.com/solrun18/infrastructure

**Comment by ironpeak** [comment]
> 
> 
> queenteam
> https://github.com/solrun18/infrastructure

your project isn't private

**Comment by magnsve** [comment]
pair5
https://github.com/birtaosk93/infrastructure

**Comment by Izabela17** [comment]
> > queenteam
> > https://github.com/solrun18/infrastructure
> 
> your project isn't private

It should be private now

**Comment by baldurhar18** [comment]
https://github.com/asgeiro/infrastructure

pair8

**Comment by ArnthorDadi** [comment]
https://github.com/ArnthorDadi/infrastructure

ikea

**Comment by aronhr** [comment]
bois

https://github.com/aronhr/infrastructure

**Comment by stefank17** [comment]
pair3
https://github.com/stefank17/infrastructure

**Comment by baldvinw** [comment]
https://github.com/baldvinw/infrastructure

pair9

**Comment by thoalr** [comment]
pair10
https://github.com/thoalr/infrastructure

**Comment by kthorri** [comment]
You might need to remove a line from ~/.ssh/known_hosts

**Comment by tinnarve** [comment]
nan-braud
https://github.com/koffa95/infrastructure

**Comment by ingibjorg88** [comment]
what
https://github.com/ingibjorg88/infrastructure

**Comment by palli710** [comment]
pair4
https://github.com/palli710/infrastructure

**Comment by soring** [comment]
cicd
https://github.com/ContinuousInvestigationContinuousDebug/infrastructure

**Comment by arnara18** [comment]
two
https://github.com/arnara18/infrastructure

**Comment by soleyhr** [comment]
clueless 
https://github.com/soleyhr/infrastructure
