### ISSUE TITLE
Linux reinstall

### ISSUE THREAD

**Issue by ingibjorg88** [hgop/syllabus-2020#30]
Hi, 
I need help with reinstalling Linux in a dual boot situation (aldready have Ubuntu on a partition but need to set up again). 

I have created a new usb to boot with (using rufus/ Ubuntu 20.10). Tried to use write ISO image- it failed a coupe of times so I tested writing in DD image mode- that worked).

Using PC (probably obvoius)..
I don't know of anything that should be preventing the set up- but when I reach the menu on startup and select the usb to boot from, nothing happens. 

I can choose to edit at some point and enter GNU grub 2.02 (like this: https://images.gutefrage.net/media/fragen/bilder/gnu-grub-version-202-beta2-29ubuntu03/0_original.jpg?v=1510761051000 )

Thank you

**Comment by ironpeak** [comment]
You should be using 20.04 :)

**Comment by ingibjorg88** [comment]
ait :)
https://media.giphy.com/media/T8Dhl1KPyzRqU/giphy.gif
