### ISSUE TITLE
Erum að fá villu í pytest --cov=connect4 tests/unit

### ISSUE THREAD

**Issue by lilja16** [hgop/syllabus-2020#32]
![villa](https://user-images.githubusercontent.com/34062832/101014336-a0be7880-355d-11eb-9e83-ddd2cb0b2ca8.png)

Eiga þær að vera?

**Comment by ironpeak** [comment]
sýnist þið hafa dottið úr virtualenv í python.

ef það er nú þegar til staðar:

~~~bash
bash .venv/bin/activate
~~~

annars þurfið þið að búa til nýtt venv:

https://github.com/hgop/connect-four-server-base
