### ISSUE TITLE
2 x connenct4 möppur?

### ISSUE THREAD

**Issue by soleyhr** [hgop/syllabus-2020#33]
hæhæ 
eiga að vera tvær möppur af connect4?

<img width="327" alt="Screen Shot 2020-12-03 at 12 20 20" src="https://user-images.githubusercontent.com/34030123/101017570-2ba17200-3562-11eb-9967-b823d70fc2d3.png">

**Comment by ironpeak** [comment]
Átti að heita scripts, búið að laga núna 👍
