### ISSUE TITLE
acceptance test fails

### ISSUE THREAD

**Issue by baldurhar18** [hgop/syllabus-2020#35]
![image](https://user-images.githubusercontent.com/42969947/101064424-e2feae80-358b-11eb-8c7e-e03cd72332c2.png)
![image](https://user-images.githubusercontent.com/42969947/101064673-2ce79480-358c-11eb-9112-276ee3f486a0.png)
getur einhver sagt mér hvað er að klikka á leiðinni í gegnum circleci?

**Comment by ironpeak** [comment]
sýnist vanta environment variable fyrir acceptance test jobbið

**Comment by baldurhar18** [comment]
![image](https://user-images.githubusercontent.com/42969947/101065575-38878b00-358d-11eb-9e13-92470cced207.png)
er með það svona núna

**Comment by ironpeak** [comment]
acceptance test ættu ekki að vera að nota docker-publisher sem executor
