### ISSUE TITLE
pip not able to install any packages

### ISSUE THREAD

**Issue by nannalop** [hgop/syllabus-2020#36]
When trying to run
    pip install -r requirements.txt
inside the virtualenv

I get the output:

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd411c5b730>: Failed to establish a new connection: [Errno 111] Connection refused'))': /simple/mypy/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd411c4f9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))': /simple/mypy/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd411c4f130>: Failed to establish a new connection: [Errno 111] Connection refused'))': /simple/mypy/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd411c4f160>: Failed to establish a new connection: [Errno 111] Connection refused'))': /simple/mypy/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd411c4f1c0>: Failed to establish a new connection: [Errno 111] Connection refused'))': /simple/mypy/
ERROR: Could not find a version that satisfies the requirement mypy==0.790 (from -r requirements_dev.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for mypy==0.790 (from -r requirements_dev.txt (line 1))

I am running
Ubuntu 20.04
Python 3.8.5
pip 20.0.2
Not behind any proxy and not using vpn

I have tried reinstalling pip a couple of times and have an alias on pip3 which is why pip should work. I have also tried upgrading but always get that I am already up to date in the output.

Has this happened to anyone else?
Er nauðsynlegt að hafa þetta gangandi fyrir acceptance testin?

**Comment by ironpeak** [comment]
have you tried deleting your virtualenv, and installing the requirements again?

~~~bash
rm -rf .venv
# setup venv again
~~~

**Comment by nannalop** [comment]
Forgot to mention it also happens outside of the virtualenv!

**Comment by ironpeak** [comment]
have you made any changes to the requirements files?
does this work in CI?
does this work for your partner?

**Comment by nannalop** [comment]
1. No, I have not made any changes to them.
2. Not sure what you mean but as far as we know the CI runs without issues although we seem to be deploying the wrong docker image.
3. Yes, it works for her.

Further details/updates on this issue:
I created a global pip.config file since no pip.config file existed in my system, but I can not find out how to set the no_proxy environment variable to true (nowhere on the pip documentation).

**Comment by ironpeak** [comment]
Have you tried restarting the computer?

Do you have a weak internet connection?

**Comment by nannalop** [comment]
Restarted maybe about 4 times yesterday. Tried hotspotting my phone at school and tried everything at home as well.

**Comment by ironpeak** [comment]
Ignore this for now and we'll take a look during the practical session.
