### ISSUE TITLE
Acceptance test : status code 503

### ISSUE THREAD

**Issue by holmar18** [hgop/syllabus-2020#37]
`_________________________________ test_status __________________________________

    def test_status():
        response = requests.get(config.API_URL + "/status")
          assert "Running" == response.text
        AssertionError: assert 'Running' == '<html>\r\n<h...\n</html>\r\n'
          + Running
          - <html>
          - <head><title>503 Service Temporarily Unavailable</title></head>
          - <body>
          - <center><h1>503 Service Temporarily Unavailable</h1></center>
          - <hr><center>nginx/1.19.0</center>
          - </body>
          - </html>`

We are getting status of 503 and are having a hard time trouble shooting. Any idea why this happens?

**Comment by Izabela17** [comment]
When you run this command: kubectl get pods -n acceptance 
do you see your acceptance pods running?

**Comment by holmar18** [comment]
oki thanks, i can see there that its restarting again and again.
