### ISSUE TITLE
Day 01 - Lab assignment

### ISSUE THREAD

**Issue by birtaosk93** [hgop/syllabus-2020#4]
Birta Ósk Theodórsdóttir - birtaot18@ru.is
Magnús Sveinsson - magnus10@ru.is
https://github.com/birtaosk93/infrastructure

**Comment by ironpeak** [comment]
The handin is weekly, on Fridays :)

**Comment by birtaosk93** [comment]
Það stendur samt í verkefnalýsingunni að það eigi að búa til issue:)

**Comment by ironpeak** [comment]
You are right 💯
