### ISSUE TITLE
Error: could not connect to the database

### ISSUE THREAD

**Issue by stefank17** [hgop/syllabus-2020#40]
I get this when doing: kubectl logs pod/pod_name
![image](https://user-images.githubusercontent.com/42969936/101201846-41955c80-3660-11eb-8ed9-b8db868382f5.png)

Does anyone have idea why I am not able to connect to the database and how I could connect it?

**Comment by ironpeak** [comment]
Is the name of the database pod connect-four-server-db?

If it is you might not have enabled dns for microk8s:

https://github.com/hgop/syllabus-2020/blob/master/assignments/week-02/day-06/README.md

Part 2 - Update your kubernetes cluster

**Comment by stefank17** [comment]
I probably made a mistake by creating another database
The name of the database should be connect-four-database-acceptance, related to the image above
I already enabled dns

Right now we have connect4, and client-four-server-production running but the connect-four-server-acceptance is showing 503 sometimes 502

We have running pod both for the database and the game-server app in namespace acceptance. They both show that their running without crashing, but I dont see any request being sent with the logs command, when visiting the acceptance server

**Comment by ironpeak** [comment]
In the logs for you server, does the server say it has started or is the log empty?

If they logs are empty the server hasn't managed to connect with the database.

If the server has started it is connected to the database and rdy to accept connections.

**Comment by stefank17** [comment]
The log is not empty, but there is error with connecting to the database

![image](https://user-images.githubusercontent.com/42969936/101222153-166f3500-3681-11eb-8b92-6a54cc3a173e.png)

It doesn't recieve any requests, when I visit the site I get 503

**Comment by ironpeak** [comment]
I send you a zoom link on slack
