### ISSUE TITLE
Circleci fyrir server hætt að virka 

### ISSUE THREAD

**Issue by soleyhr** [hgop/syllabus-2020#41]
Við höfum ekkert verið að commita inná Server núna í 6 tíma en allt í einu hætti hann að virka :( hvað getur verið vandamálið?
<img width="947" alt="Screen Shot 2020-12-04 at 22 27 13" src="https://user-images.githubusercontent.com/34030123/101221616-f0956080-367f-11eb-8fc0-06334a7e06e4.png">

<img width="998" alt="Screen Shot 2020-12-04 at 22 20 58" src="https://user-images.githubusercontent.com/34030123/101221502-baf07780-367f-11eb-95a8-1e04fe5e4e76.png">
<img width="904" alt="Screen Shot 2020-12-04 at 22 23 25" src="https://user-images.githubusercontent.com/34030123/101221512-c04dc200-367f-11eb-9cdf-fb08f57df5f1.png">

**Comment by ironpeak** [comment]
sýnist þetta bara vera random villa, getur prófað að retry-a
