### ISSUE TITLE
Villa í pipeline

### ISSUE THREAD

**Issue by lilja16** [hgop/syllabus-2020#42]
Við vorum að klára:
Now create the production database again like you did on day 6, you do not have to do this for the acceptance and capacity environments, the CI pipeline will recreate them.
Commit the code changes to github, the pipeline should work.
Þessi skref en pipelineið okkar failar á lint og þessi villa kemur

![image](https://user-images.githubusercontent.com/34062832/101386628-57e82600-38b5-11eb-80ad-a73bc8db588b.png)

**Comment by lilja16** [comment]
Tókum út annað arguementið (gameId) í get_player og komumst þá lengra en fáum villu í 
acceptance testinu.
![image](https://user-images.githubusercontent.com/34062832/101391564-6a199280-38bc-11eb-9e64-16e090308b07.png)

**Comment by soring** [comment]
Voru þið búin að útfæra TODO föllin sem komu með kóðanum ?

**Comment by lilja16** [comment]
Já vorum búnar að því :)

**Comment by ironpeak** [comment]
eru poddarnir í gangi í acceptance namespace-inu?

**Comment by lilja16** [comment]
![image](https://user-images.githubusercontent.com/34062832/101402389-9c7ebc00-38cb-11eb-805f-0aa5bf418231.png)
Koma allavega upp ef við gerum get pods :$

**Comment by ironpeak** [comment]
þú þarft að tilgreina `-n acceptance` til þess að skoða pods í acceptance :)

**Comment by soleyhr** [comment]
<img width="674" alt="Screen Shot 2020-12-08 at 08 33 32" src="https://user-images.githubusercontent.com/34030123/101459419-23658000-3930-11eb-8ca2-3c5b360ef135.png">

**Comment by ironpeak** [comment]
~~~bash
kubectl logs connect-four-server-acceptance-727f8ccc58-28qkv -n acceptance
~~~

**Comment by lilja16** [comment]
![image](https://user-images.githubusercontent.com/34062832/101473654-fde17200-3941-11eb-9bd7-c95651fbc0ed.png)

Kemur svona 😖
