### ISSUE TITLE
500 internal error on any game requests on connect4

### ISSUE THREAD

**Issue by tinnarve** [hgop/syllabus-2020#46]
Eftir aö hafa klárað að setja upp nýja databasinn frá degi 11 þá hætti client að virka. Server, Client og db eru að keyra samkvæmt kubectl get pods en um leið og maður reynir að byrja leik þá er það bara react sem renderar en ekkert app logic virkar almennilega.

client logs
![image](https://user-images.githubusercontent.com/34030683/101556229-4d5f8680-39b2-11eb-91fb-9adfd78a27dd.png)

server logs
![image](https://user-images.githubusercontent.com/34030683/101556358-91528b80-39b2-11eb-8749-dccbec95f16e.png)

db logs
![image](https://user-images.githubusercontent.com/34030683/101556408-b21ae100-39b2-11eb-87ac-856c1da51f0f.png)

EDIT ---
Eftir smá bið við að reyna að joina muliplier leik þá kom þessi error upp
![image](https://user-images.githubusercontent.com/34030683/101556807-8d733900-39b3-11eb-8774-38a4c6ecfe93.png)

**Comment by Fanneyyy** [comment]
You can use this server: http://connect-four-server-production.dreamteam.hgopteam.com/ for your client and see if the client works. You can continue with the e2e using that server until yours is fixed.

The server seems to be broken, the logs are not pointing to the issue, if you run your server locally you should better see what the issue is.

**Comment by tinnarve** [comment]
serverinn er alltaf að skila password authentication failed
server_1    | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "postgres"
er að keyra databse locally og búin að henda öllum útaf kubectl til öryggis. Er ekki alveg viss hvernig ég laga þetta :(

**Comment by Fanneyyy** [comment]
Hljómar eins og þið hafið verið með vitlaus variables í path þegar þið bjugguð til databaseinn. Ég mæli með að þið hendið honum alveg og setjið hann upp aftur, getið hent databaseinum eins og kemur fram í Day 11:
```
# production
## deployment - scale it down to 0 pods so that it does not recreate the old database schema.
kubectl scale deployment connect-four-server-production --replicas=0
## database
kubectl delete service               connect-four-database-production
kubectl delete statefulset           connect-four-database-production
kubectl delete persistentvolumeclaim connect-four-database-production
kubectl delete persistentvolume      connect-four-database-production
kubectl delete storageclass          connect-four-database-production
kubectl delete configmap             connect-four-database-production
```

Gera svo eins og í degi 2:
Þið þurfið að hafa þessi í path sömu og eru í Circle CI:
```
export DATABASE_USERNAME=$(echo -n [YOUR_CHOSEN_USERNAME] | base64)
export DATABASE_PASSWORD=$(echo -n [YOUR_CHOSEN_PASSWORD] | base64)
export SECRET_KEY=$(echo -n [YOUR_CHOSEN_SECRET_KEY] | base64)
```
Og búa til database:
```
bash scripts/create_database.sh default production
```

**Comment by tinnarve** [comment]
Hann keyrðist upp núna en við erum að fá sömu error skilaboð og í hinum logs

e0b210adead3_connect-four-server_server_1 | 172.19.0.1 - - [09/Dec/2020 17:38:01] "GET / HTTP/1.1" 200 -
e0b210adead3_connect-four-server_server_1 | 172.19.0.1 - - [09/Dec/2020 17:38:01] "GET /favicon.ico HTTP/1.1" 404 -
e0b210adead3_connect-four-server_server_1 | 172.19.0.1 - - [09/Dec/2020 17:39:57] "OPTIONS //create_game HTTP/1.1" 200 -
e0b210adead3_connect-four-server_server_1 | 172.19.0.1 - - [09/Dec/2020 17:39:57] "POST //create_game HTTP/1.1" 500 -.

**Comment by tinnarve** [comment]
held þetta sé komið í lag. Pipeline test í gangi

**Comment by tinnarve** [comment]
þetta er komið í lag. Takk fyrir hjálpina :)
