### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by lilja16** [hgop/syllabus-2020#9]
Í morgun á zoom voru nemendur að ræða að búa til slack síðu fyrir áfangann er hún komin upp? :)
Fannst eins og Hannes ætlaði að tilkynna það en finn ekkert um það.

**Comment by hap2000** [comment]
Hann Jón stofnaði þetta og hér er linkurinn. Ég mun líka senda póst á alla:
https://join.slack.com/t/soringworkspace/shared_invite/zt-jj7aqu6c-sKSA_vuz4p4oDqMHoGdDWA
